---
title: Een geluid opnemen
hero_image: images/banner.png
description: Een geluid opnemen
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Een geluid opnemen
