---
title: Enregistrer un son
hero_image: images/banner.png
description: Enregistrer le son
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Enregistrer un son
